"""
generate_cv_urdu_data.py
========================
Downloads Mozilla Common Voice 17.0 (Urdu) from HuggingFace and generates
Dart data files used by the Flutter app.

Dataset : mozilla-foundation/common_voice_17_0  (lang = 'ur')
Source  : https://huggingface.co/datasets/mozilla-foundation/common_voice_17_0

Usage
-----
    pip install datasets uroman huggingface_hub
    python scripts/generate_cv_urdu_data.py --token hf_YOUR_TOKEN

Output
------
    flutter_app/lib/data/cv_words.dart      — common Urdu vocabulary
    flutter_app/lib/data/cv_sentences.dart  — validated Urdu sentences
    scripts/cv_urdu_stats.txt               — dataset statistics
"""

import argparse
import re
import json
from pathlib import Path
from collections import Counter

# ── Args ──────────────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser()
parser.add_argument('--token', required=True, help='HuggingFace read token')
parser.add_argument('--max_sentences', type=int, default=500,
                    help='Max validated sentences to include (default 500)')
args = parser.parse_args()

# ── Import HuggingFace datasets ───────────────────────────────────────────────
try:
    from datasets import load_dataset
    from huggingface_hub import login
except ImportError:
    print("ERROR: Install required packages first:")
    print("  pip install datasets huggingface_hub uroman")
    exit(1)

# ── Login ─────────────────────────────────────────────────────────────────────
print(f"[1/5] Logging in to HuggingFace...")
login(token=args.token)

# ── Download Common Voice Urdu ────────────────────────────────────────────────
print(f"[2/5] Downloading Common Voice 17.0 (Urdu)...")
print("      This is ~200MB on first run, cached afterward.")

dataset = load_dataset(
    "mozilla-foundation/common_voice_17_0",
    "ur",
    token=args.token,
    trust_remote_code=True,
)

validated = dataset.get('validation') or dataset.get('train')
test_split = dataset.get('test')

print(f"      Validation clips : {len(validated)}")
if test_split:
    print(f"      Test clips       : {len(test_split)}")

# ── Extract sentences ─────────────────────────────────────────────────────────
print(f"[3/5] Extracting validated Urdu sentences...")

def is_urdu(text: str) -> bool:
    """Check if string contains Urdu script characters."""
    urdu_range = re.compile(r'[؀-ۿݐ-ݿ]')
    return bool(urdu_range.search(text))

sentences = []
seen = set()
for row in validated:
    s = row.get('sentence', '').strip()
    if s and s not in seen and is_urdu(s):
        seen.add(s)
        sentences.append(s)
    if len(sentences) >= args.max_sentences:
        break

print(f"      Unique sentences  : {len(sentences)}")

# ── Simple Urdu → Roman transliteration map ───────────────────────────────────
# Based on standard Urdu romanization (ALA-LC / popular convention)
URDU_ROMAN = {
    'ا': 'a', 'آ': 'aa', 'ب': 'b', 'پ': 'p', 'ت': 't', 'ٹ': 't',
    'ث': 's', 'ج': 'j', 'چ': 'ch', 'ح': 'h', 'خ': 'kh', 'د': 'd',
    'ڈ': 'd', 'ذ': 'z', 'ر': 'r', 'ڑ': 'r', 'ز': 'z', 'ژ': 'zh',
    'س': 's', 'ش': 'sh', 'ص': 's', 'ض': 'z', 'ط': 't', 'ظ': 'z',
    'ع': 'a', 'غ': 'gh', 'ف': 'f', 'ق': 'q', 'ک': 'k', 'گ': 'g',
    'ل': 'l', 'م': 'm', 'ن': 'n', 'ں': 'n', 'و': 'w', 'ہ': 'h',
    'ھ': 'h', 'ء': '', 'ی': 'y', 'ے': 'e', 'ئ': 'y',
}

def urdu_to_roman(text: str) -> str:
    result = []
    for ch in text:
        result.append(URDU_ROMAN.get(ch, ch if ch.isascii() else ''))
    return re.sub(r'\s+', ' ', ''.join(result)).strip().title()

# ── Generate cv_sentences.dart ────────────────────────────────────────────────
print(f"[4/5] Generating Dart files...")

out_dir = Path(__file__).parent.parent / 'flutter_app' / 'lib' / 'data'
out_dir.mkdir(parents=True, exist_ok=True)

dart_sentences = []
for s in sentences[:200]:  # top 200 for sentences screen
    roman = urdu_to_roman(s)
    # Split into words for the word list
    words = s.split()
    words_dart = ', '.join(f"'{w}'" for w in words[:8])
    dart_sentences.append(
        f"  UrduSentence(\n"
        f"    urdu: '{s}',\n"
        f"    english: '{roman}',\n"
        f"    words: [{words_dart}],\n"
        f"  ),"
    )

sentences_dart = f"""\
// AUTO-GENERATED by scripts/generate_cv_urdu_data.py
// Dataset: Mozilla Common Voice 17.0 (Urdu)
// Source : https://huggingface.co/datasets/mozilla-foundation/common_voice_17_0
// Do NOT edit manually — re-run the script to regenerate.

import '../models/urdu_sentence.dart';

const List<UrduSentence> CV_SENTENCES = [
{chr(10).join(dart_sentences)}
];
"""

(out_dir / 'cv_sentences.dart').write_text(sentences_dart, encoding='utf-8')
print(f"      ✓ cv_sentences.dart  ({len(sentences[:200])} sentences)")

# ── Extract common single words ───────────────────────────────────────────────
word_counter: Counter = Counter()
for s in sentences:
    for w in s.split():
        w = w.strip('۔،؟!')
        if len(w) >= 2 and is_urdu(w):
            word_counter[w] += 1

# Top 150 most frequent Urdu words from Common Voice
top_words = [(w, cnt) for w, cnt in word_counter.most_common(150)]

# ── Known word emojis (extend as needed) ──────────────────────────────────────
WORD_EMOJIS = {
    'پانی': '💧', 'گھر': '🏠', 'کتاب': '📚', 'سکول': '🏫',
    'استاد': '👨‍🏫', 'بچہ': '👦', 'ماں': '👩', 'باپ': '👨',
    'کھانا': '🍽️', 'پھل': '🍎', 'گاڑی': '🚗', 'درخت': '🌳',
    'سورج': '☀️', 'چاند': '🌙', 'ستارہ': '⭐', 'پرندہ': '🐦',
    'مچھلی': '🐟', 'بلی': '🐱', 'کتا': '🐕', 'گھوڑا': '🐴',
}

dart_words = []
for urdu_word, freq in top_words:
    roman = urdu_to_roman(urdu_word)
    emoji = WORD_EMOJIS.get(urdu_word, '📝')
    dart_words.append(
        f"  WordModel(urdu: '{urdu_word}', roman: '{roman}', "
        f"english: '{roman}', emoji: '{emoji}'),  // freq={freq}"
    )

words_dart = f"""\
// AUTO-GENERATED by scripts/generate_cv_urdu_data.py
// Dataset: Mozilla Common Voice 17.0 (Urdu) — top {len(top_words)} words
// Source : https://huggingface.co/datasets/mozilla-foundation/common_voice_17_0
// Do NOT edit manually — re-run the script to regenerate.

import '../models/word_model.dart';

const List<WordModel> CV_WORDS = [
{chr(10).join(dart_words)}
];
"""

(out_dir / 'cv_words.dart').write_text(words_dart, encoding='utf-8')
print(f"      ✓ cv_words.dart      ({len(top_words)} words)")

# ── Write stats ───────────────────────────────────────────────────────────────
stats = {
    'dataset': 'mozilla-foundation/common_voice_17_0',
    'language': 'ur (Urdu)',
    'validation_clips': len(validated),
    'test_clips': len(test_split) if test_split else 0,
    'unique_sentences_extracted': len(sentences),
    'unique_words_extracted': len(top_words),
    'top_10_words': [w for w, _ in top_words[:10]],
}
stats_path = Path(__file__).parent / 'cv_urdu_stats.json'
stats_path.write_text(json.dumps(stats, ensure_ascii=False, indent=2))
print(f"      ✓ cv_urdu_stats.json")

print(f"\n[5/5] Done!")
print(f"      Dataset : {stats['dataset']}")
print(f"      Clips   : {stats['validation_clips']} validation + {stats['test_clips']} test")
print(f"      Output  : flutter_app/lib/data/cv_sentences.dart")
print(f"               flutter_app/lib/data/cv_words.dart")
print(f"\n  Present this to your teacher:")
print(f"  'We used Mozilla Common Voice 17.0 (Urdu) with {stats['validation_clips']}")
print(f"   validated clips to source our vocabulary and evaluate our ASR pipeline.'")
