export const FULL_ALPHABET = [
  { u:"ا", r:"Alif",        ex:"اونٹ",   exR:"Oont",   eng:"Camel",      emoji:"🐪" },
  { u:"آ", r:"Alif-Mad",    ex:"آم",     exR:"Aam",    eng:"Mango",      emoji:"🥭" },
  { u:"ب", r:"Bay",         ex:"بلی",    exR:"Billi",  eng:"Cat",        emoji:"🐱" },
  { u:"پ", r:"Pay",         ex:"پانی",   exR:"Paani",  eng:"Water",      emoji:"💧" },
  { u:"ت", r:"Tay",         ex:"تتلی",   exR:"Titli",  eng:"Butterfly",  emoji:"🦋" },
  { u:"ٹ", r:"Ttay",        ex:"ٹوپی",   exR:"Topi",   eng:"Hat",        emoji:"🎩" },
  { u:"ث", r:"Say",         ex:"ثمر",    exR:"Samar",  eng:"Fruit",      emoji:"🍎" },
  { u:"ج", r:"Jeem",        ex:"جہاز",   exR:"Jahaaz", eng:"Aeroplane",  emoji:"✈️" },
  { u:"چ", r:"Chay",        ex:"چاند",   exR:"Chaand", eng:"Moon",       emoji:"🌙" },
  { u:"ح", r:"Hay",         ex:"حلوہ",   exR:"Halwa",  eng:"Halwa",      emoji:"🍮" },
  { u:"خ", r:"Khay",        ex:"خرگوش",  exR:"Khargosh",eng:"Rabbit",    emoji:"🐰" },
  { u:"د", r:"Daal",        ex:"دودھ",   exR:"Doodh",  eng:"Milk",       emoji:"🥛" },
  { u:"ڈ", r:"Ddaal",       ex:"ڈبہ",    exR:"Dabba",  eng:"Box",        emoji:"📦" },
  { u:"ذ", r:"Zaal",        ex:"ذہین",   exR:"Zaheen", eng:"Intelligent",emoji:"🧠" },
  { u:"ر", r:"Ray",         ex:"ریچھ",   exR:"Reechh", eng:"Bear",       emoji:"🐻" },
  { u:"ڑ", r:"Rray",        ex:"لڑکا",   exR:"Larka",  eng:"Boy",        emoji:"👦" },
  { u:"ز", r:"Zay",         ex:"زیبرا",  exR:"Zebra",  eng:"Zebra",      emoji:"🦓" },
  { u:"ژ", r:"Zhay",        ex:"ژالہ",   exR:"Zhaala", eng:"Hail",       emoji:"🌨️" },
  { u:"س", r:"Seen",        ex:"سیب",    exR:"Saib",   eng:"Apple",      emoji:"🍎" },
  { u:"ش", r:"Sheen",       ex:"شیر",    exR:"Sher",   eng:"Lion",       emoji:"🦁" },
  { u:"ص", r:"Suaad",       ex:"صابن",   exR:"Saabun", eng:"Soap",       emoji:"🧼" },
  { u:"ض", r:"Zuaad",       ex:"ضرور",   exR:"Zaroor", eng:"Necessary",  emoji:"✔️" },
  { u:"ط", r:"Toay",        ex:"طوطا",   exR:"Tota",   eng:"Parrot",     emoji:"🦜" },
  { u:"ظ", r:"Zoay",        ex:"ظالم",   exR:"Zaalim", eng:"Cruel",      emoji:"😈" },
  { u:"ع", r:"Ain",         ex:"عقاب",   exR:"Uqaab",  eng:"Eagle",      emoji:"🦅" },
  { u:"غ", r:"Ghain",       ex:"غبارہ",  exR:"Ghubaara",eng:"Balloon",   emoji:"🎈" },
  { u:"ف", r:"Fay",         ex:"فیل",    exR:"Feel",   eng:"Elephant",   emoji:"🐘" },
  { u:"ق", r:"Qaaf",        ex:"قلم",    exR:"Qalam",  eng:"Pen",        emoji:"✏️" },
  { u:"ک", r:"Kaaf",        ex:"کتاب",   exR:"Kitaab", eng:"Book",       emoji:"📚" },
  { u:"گ", r:"Gaaf",        ex:"گائے",   exR:"Gaay",   eng:"Cow",        emoji:"🐄" },
  { u:"ل", r:"Laam",        ex:"لمبا",   exR:"Lamba",  eng:"Tall",       emoji:"📏" },
  { u:"م", r:"Meem",        ex:"مچھلی",  exR:"Machhli",eng:"Fish",       emoji:"🐟" },
  { u:"ن", r:"Noon",        ex:"ناشتہ",  exR:"Naashta",eng:"Breakfast",  emoji:"🍳" },
  { u:"ں", r:"Noon Ghunna", ex:"ہاں",    exR:"Haan",   eng:"Yes",        emoji:"✅" },
  { u:"و", r:"Wow",         ex:"وقت",    exR:"Waqt",   eng:"Time",       emoji:"⏰" },
  { u:"ہ", r:"Hay",         ex:"ہاتھی",  exR:"Haathi", eng:"Elephant",   emoji:"🐘" },
  { u:"ھ", r:"Do-Chashmi-Hay",ex:"بھالو",exR:"Bhaloo", eng:"Bear",       emoji:"🐻" },
  { u:"ء", r:"Hamza",       ex:"جزء",    exR:"Juz",    eng:"Part",       emoji:"📌" },
  { u:"ی", r:"Choti Yay",   ex:"یاد",    exR:"Yaad",   eng:"Memory",     emoji:"💭" },
  { u:"ے", r:"Bari Yay",    ex:"لڑکے",   exR:"Larke",  eng:"Boys",       emoji:"👦" },
];
 
export const WORDS = [
  // Animals
  { u:"بلی",    r:"Billi",    eng:"Cat",        emoji:"🐱", cat:"جانور", level:"easy",   phonemes:["bi","l","li"],    target:"billi" },
  { u:"کتا",    r:"Kutta",    eng:"Dog",        emoji:"🐶", cat:"جانور", level:"easy",   phonemes:["ku","tt","a"],    target:"kutta" },
  { u:"شیر",    r:"Sher",     eng:"Lion",       emoji:"🦁", cat:"جانور", level:"easy",   phonemes:["sh","er"],        target:"sher" },
  { u:"ہاتھی",  r:"Haathi",   eng:"Elephant",   emoji:"🐘", cat:"جانور", level:"medium", phonemes:["haa","th","i"],   target:"haathi" },
  { u:"بندر",   r:"Bandar",   eng:"Monkey",     emoji:"🐒", cat:"جانور", level:"medium", phonemes:["ban","dar"],      target:"bandar" },
  { u:"مچھلی",  r:"Machhli",  eng:"Fish",       emoji:"🐟", cat:"جانور", level:"medium", phonemes:["mach","hli"],     target:"machhli" },
  { u:"خرگوش",  r:"Khargosh", eng:"Rabbit",     emoji:"🐰", cat:"جانور", level:"hard",   phonemes:["khar","gosh"],    target:"khargosh" },
  { u:"زیبرا",  r:"Zebra",    eng:"Zebra",      emoji:"🦓", cat:"جانور", level:"hard",   phonemes:["ze","bra"],       target:"zebra" },
  // Food
  { u:"آم",     r:"Aam",      eng:"Mango",      emoji:"🥭", cat:"کھانا", level:"easy",   phonemes:["aa","m"],         target:"aam" },
  { u:"سیب",    r:"Saib",     eng:"Apple",      emoji:"🍎", cat:"کھانا", level:"easy",   phonemes:["sa","ib"],        target:"saib" },
  { u:"دودھ",   r:"Doodh",    eng:"Milk",       emoji:"🥛", cat:"کھانا", level:"easy",   phonemes:["doo","dh"],       target:"doodh" },
  { u:"روٹی",   r:"Roti",     eng:"Bread",      emoji:"🫓", cat:"کھانا", level:"easy",   phonemes:["ro","ti"],        target:"roti" },
  { u:"چاول",   r:"Chawal",   eng:"Rice",       emoji:"🍚", cat:"کھانا", level:"medium", phonemes:["cha","wal"],      target:"chawal" },
  { u:"کیلا",   r:"Kela",     eng:"Banana",     emoji:"🍌", cat:"کھانا", level:"easy",   phonemes:["ke","la"],        target:"kela" },
  { u:"انگور",  r:"Angoor",   eng:"Grapes",     emoji:"🍇", cat:"کھانا", level:"medium", phonemes:["an","goor"],      target:"angoor" },
  { u:"گاجر",   r:"Gajar",    eng:"Carrot",     emoji:"🥕", cat:"کھانا", level:"medium", phonemes:["ga","jar"],       target:"gajar" },
  // Nature
  { u:"سورج",   r:"Suraj",    eng:"Sun",        emoji:"☀️", cat:"فطرت", level:"easy",   phonemes:["su","raj"],       target:"suraj" },
  { u:"چاند",   r:"Chaand",   eng:"Moon",       emoji:"🌙", cat:"فطرت", level:"easy",   phonemes:["chaa","nd"],      target:"chaand" },
  { u:"درخت",   r:"Darakht",  eng:"Tree",       emoji:"🌳", cat:"فطرت", level:"medium", phonemes:["da","rakht"],     target:"darakht" },
  { u:"پہاڑ",   r:"Pahar",    eng:"Mountain",   emoji:"⛰️", cat:"فطرت", level:"medium", phonemes:["pa","har"],       target:"pahar" },
  { u:"ندی",    r:"Nadi",     eng:"River",      emoji:"🏞️", cat:"فطرت", level:"easy",   phonemes:["na","di"],        target:"nadi" },
  { u:"پھول",   r:"Phool",    eng:"Flower",     emoji:"🌸", cat:"فطرت", level:"easy",   phonemes:["phoo","l"],       target:"phool" },
  { u:"بارش",   r:"Barish",   eng:"Rain",       emoji:"🌧️", cat:"فطرت", level:"medium", phonemes:["ba","rish"],      target:"barish" },
  { u:"آسمان",  r:"Aasmaan",  eng:"Sky",        emoji:"🌤️", cat:"فطرت", level:"medium", phonemes:["aas","maan"],     target:"aasmaan" },
  // Things
  { u:"کتاب",   r:"Kitaab",   eng:"Book",       emoji:"📚", cat:"چیزیں", level:"easy",   phonemes:["ki","taab"],      target:"kitaab" },
  { u:"قلم",    r:"Qalam",    eng:"Pen",        emoji:"✏️", cat:"چیزیں", level:"easy",   phonemes:["qa","lam"],       target:"qalam" },
  { u:"گھڑی",   r:"Ghadi",    eng:"Watch",      emoji:"⌚", cat:"چیزیں", level:"medium", phonemes:["gha","di"],       target:"ghadi" },
  { u:"تھیلا",  r:"Theela",   eng:"Bag",        emoji:"👜", cat:"چیزیں", level:"easy",   phonemes:["thee","la"],      target:"theela" },
  { u:"گھر",    r:"Ghar",     eng:"House",      emoji:"🏠", cat:"چیزیں", level:"easy",   phonemes:["gha","r"],        target:"ghar" },
  { u:"دروازہ", r:"Darwaza",  eng:"Door",       emoji:"🚪", cat:"چیزیں", level:"medium", phonemes:["dar","wa","za"],  target:"darwaza" },
  { u:"میز",    r:"Mez",      eng:"Table",      emoji:"🪑", cat:"چیزیں", level:"easy",   phonemes:["me","z"],         target:"mez" },
  { u:"کرسی",   r:"Kursi",    eng:"Chair",      emoji:"🪑", cat:"چیزیں", level:"easy",   phonemes:["kur","si"],       target:"kursi" },
  // Body
  { u:"ہاتھ",   r:"Haath",    eng:"Hand",       emoji:"✋", cat:"جسم",   level:"easy",   phonemes:["haa","th"],       target:"haath" },
  { u:"آنکھ",   r:"Aankh",    eng:"Eye",        emoji:"👁️", cat:"جسم",   level:"easy",   phonemes:["aan","kh"],       target:"aankh" },
  { u:"کان",    r:"Kaan",     eng:"Ear",        emoji:"👂", cat:"جسم",   level:"easy",   phonemes:["kaa","n"],        target:"kaan" },
  { u:"ناک",    r:"Naak",     eng:"Nose",       emoji:"👃", cat:"جسم",   level:"easy",   phonemes:["naa","k"],        target:"naak" },
  { u:"منہ",    r:"Munh",     eng:"Mouth",      emoji:"👄", cat:"جسم",   level:"easy",   phonemes:["mu","nh"],        target:"munh" },
  { u:"پیر",    r:"Pair",     eng:"Foot",       emoji:"🦶", cat:"جسم",   level:"easy",   phonemes:["pa","ir"],        target:"pair" },
  { u:"سر",     r:"Sar",      eng:"Head",       emoji:"🗣️", cat:"جسم",   level:"easy",   phonemes:["sa","r"],         target:"sar" },
  { u:"دل",     r:"Dil",      eng:"Heart",      emoji:"❤️", cat:"جسم",   level:"easy",   phonemes:["di","l"],         target:"dil" },
];
 
export const SENTENCES = [
  { u:"میرا نام احمد ہے۔",    eng:"My name is Ahmed.",         audio:"mera naam ahmad hai" },
  { u:"یہ میری کتاب ہے۔",     eng:"This is my book.",          audio:"yeh meri kitaab hai" },
  { u:"آج موسم اچھا ہے۔",     eng:"The weather is nice today.",audio:"aaj mausam acha hai" },
  { u:"مجھے پانی چاہیے۔",    eng:"I want water.",             audio:"mujhe paani chahiye" },
  { u:"استاد جی سلام۔",       eng:"Hello teacher.",            audio:"ustad ji salaam" },
  { u:"میں اسکول جاتا ہوں۔",  eng:"I go to school.",           audio:"mein school jaata hoon" },
  { u:"گھر پر امی ہیں۔",      eng:"Mum is at home.",           audio:"ghar par ami hain" },
  { u:"یہ بلی بہت پیاری ہے۔", eng:"This cat is very cute.",    audio:"yeh billi bohat pyaari hai" },
  { u:"میں پانی پیتا ہوں۔",   eng:"I drink water.",            audio:"mein paani peeta hoon" },
  { u:"آج جمعہ ہے۔",          eng:"Today is Friday.",          audio:"aaj juma hai" },
  { u:"اللہ کا شکر ہے۔",      eng:"Thanks be to God.",         audio:"allah ka shukar hai" },
  { u:"مجھے اردو پسند ہے۔",   eng:"I like Urdu.",              audio:"mujhe urdu pasand hai" },
];
 
export const COLORS = [
  { u:"سرخ",     r:"Surkh",    eng:"Red",    hex:"#e63946", light:"#ffd6d8", emoji:"🍎" },
  { u:"نیلا",    r:"Neela",    eng:"Blue",   hex:"#4361ee", light:"#d6e0ff", emoji:"🫐" },
  { u:"سبز",     r:"Sabz",     eng:"Green",  hex:"#2dc653", light:"#d0f5dc", emoji:"🍃" },
  { u:"پیلا",    r:"Peela",    eng:"Yellow", hex:"#f4d03f", light:"#fff9c4", emoji:"🌻" },
  { u:"سفید",    r:"Safaid",   eng:"White",  hex:"#f8f9fa", light:"#e9ecef", emoji:"☁️" },
  { u:"کالا",    r:"Kaala",    eng:"Black",  hex:"#212529", light:"#ced4da", emoji:"🐦‍⬛" },
  { u:"نارنجی",  r:"Naaranji", eng:"Orange", hex:"#fd7e14", light:"#ffe5cc", emoji:"🍊" },
  { u:"گلابی",   r:"Gulaabi",  eng:"Pink",   hex:"#e91e8c", light:"#ffd6ec", emoji:"🌸" },
  { u:"جامنی",   r:"Jaamni",   eng:"Purple", hex:"#7b2d8b", light:"#e8d5f5", emoji:"🍇" },
  { u:"بھورا",   r:"Bhoora",   eng:"Brown",  hex:"#795548", light:"#d7ccc8", emoji:"🪵" },
  { u:"سنہری",   r:"Sunehri",  eng:"Gold",   hex:"#f9c74f", light:"#fff3cd", emoji:"⭐" },
  { u:"آسمانی",  r:"Aasmani",  eng:"Sky Blue",hex:"#00b4d8",light:"#caf0f8", emoji:"🌤️" },
  { u:"خاکی",    r:"Khaaki",   eng:"Khaki",  hex:"#b5a642", light:"#f0ead2", emoji:"🪨" },
  { u:"سلیٹی",   r:"Sileti",   eng:"Grey",   hex:"#6c757d", light:"#dee2e6", emoji:"🌫️" },
];
 
export const FILL_BLANKS = [
  { sentence:"میرا ___ احمد ہے۔",    answer:"نام",   opts:["نام","گھر","کام","دل"],     eng:"My ___ is Ahmed." },
  { sentence:"یہ میری ___ ہے۔",      answer:"کتاب",  opts:["کتاب","بلی","میز","گھڑی"],  eng:"This is my ___." },
  { sentence:"آج موسم ___ ہے۔",      answer:"اچھا",  opts:["اچھا","برا","بڑا","چھوٹا"], eng:"Today the weather is ___." },
  { sentence:"استاد جی ___ ہیں۔",    answer:"اچھے",  opts:["اچھے","برے","بڑے","تھکے"],  eng:"The teacher is ___." },
  { sentence:"شیر ایک ___ جانور ہے۔",answer:"بڑا",   opts:["بڑا","چھوٹا","پیارا","تیز"],eng:"Lion is a ___ animal." },
  { sentence:"مجھے ___ چاہیے۔",      answer:"پانی",  opts:["پانی","کھانا","نیند","کتاب"],eng:"I want ___." },
  { sentence:"اللہ کا ___ ہے۔",      answer:"شکر",   opts:["شکر","ذکر","فکر","نظر"],    eng:"Thanks be to ___." },
  { sentence:"یہ بلی بہت ___ ہے۔",   answer:"پیاری", opts:["پیاری","بڑی","تیز","کالی"],  eng:"This cat is very ___." },
];
 
export const MATCH_DATA = [
  { emoji:"🐱", answer:"بلی",   opts:["بلی","کتا","شیر","بندر"] },
  { emoji:"🍎", answer:"سیب",   opts:["سیب","آم","کیلا","گاجر"] },
  { emoji:"☀️", answer:"سورج",  opts:["سورج","چاند","ستارہ","آسمان"] },
  { emoji:"📚", answer:"کتاب",  opts:["کتاب","قلم","میز","گھڑی"] },
  { emoji:"🥛", answer:"دودھ",  opts:["دودھ","پانی","چائے","جوس"] },
  { emoji:"🌸", answer:"پھول",  opts:["پھول","درخت","پتہ","ندی"] },
  { emoji:"🐘", answer:"ہاتھی", opts:["ہاتھی","شیر","زیبرا","بندر"] },
  { emoji:"🏠", answer:"گھر",   opts:["گھر","دروازہ","کھڑکی","چھت"] },
  { emoji:"✋", answer:"ہاتھ",  opts:["ہاتھ","پیر","آنکھ","کان"] },
  { emoji:"🌙", answer:"چاند",  opts:["چاند","سورج","ستارہ","رات"] },
  { emoji:"🦁", answer:"شیر",   opts:["شیر","چیتا","بھیڑیا","لومڑی"] },
  { emoji:"🍌", answer:"کیلا",  opts:["کیلا","آم","سیب","انگور"] },
];